### PR TITLE
Created route for checkin page and updated urls.py

### PR DESCRIPTION
**Pull request by punndcoder28**

### CODE REVIEW

**Comment by shashank-sharma** [comment]
Hey

I am really sorry but can you please revert back your changes and do the same things inside checkin app, I forgot to push my code that's why it might have confused you, I hope it will not take much of your time

In short:
1. Changes of views in /checkin/views.py
2. Create dummy template like /templates/checkin/checkin.html with hello world
3. Update routes with new views path

Again sorry for my mistake

**Comment by punndcoder28** [comment]
How can I import views from the checkin folder so that it can be used in urls.py. I tried `from ../checkin/ import checkinViews` but it gave an error. Can you help me?

**Comment by punndcoder28** [comment]
I figured out the import. 
Thanks anyway.

**Comment by shashank-sharma** [comment]
@punndcoder28 Please note that in portal/urls.py file you will:

`path('checkin/', include('checkin.urls')),`

Here we showed that we will include checkin urls in main urls and then in checkin/urls.py do normal import and all
Ref: https://docs.djangoproject.com/en/2.2/ref/urls/

**Comment by punndcoder28** [comment]
I had done something like this. 
`from checkin import views as checkinViews`
and in `urlpatterns` list I added a line for the checkin rendering like this `path('checkin/', checkinViews.check_in`.
Should I change it then?

**Comment by shashank-sharma** [comment]
@punndcoder28 Yes, so what we try to do is that whatever urls which is related to checkin, we need it in checkin/urls.py file and then in portal/urls.py file we simply route every checkin towards there

Example:
/checkin/home
/checkin/analysis

So here what happen is first portal/urls.py see /checkin/ so it will get routed to checkin/urls.py file and inside checin/urls.py you will specify /home to checkin views
I hope you understood what I am trying to say

**Comment by punndcoder28** [comment]
Thanks. This made it crystal clear. I'll be committing the changes to include this.

**Pull request closed without merging**
