### PR TITLE
push from new repo

### PR DESCRIPTION
**Pull request by borsezf2**
1. creds and keys are hidden

### CODE REVIEW

**Review by shashank-sharma — CHANGES_REQUESTED** [review]
As discussed, add package names in requirements.txt (which packages you installed explicitly to run the program)

**Comment by borsezf2** [comment]
done sir.
the json file is not needed anymore.
i let the json file and the code(only one line)(commented out) stay just in case we need them back only if we have some problem with working. once the code is tested on other systems too, i'll/anyone can remove it

**Comment by borsezf2** [comment]
looks like it's been solved

**Comment by shashank-sharma** [comment]
Great Work !

**Pull request merged**
